name: chat_app
description: "Aplicativo de chat em tempo real com Supabase e Flutter"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

# DependÃªncias principais do App
dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¹ Supabase (banco, auth e realtime)
  supabase_flutter: ^2.5.4

  # ðŸ”¹ HTTP (para chamadas Ã  Edge Function)
  http: ^1.2.0
  
  file_picker: ^10.3.7
  
  # ðŸ”¹ Image Picker (para escolher imagens do dispositivo)
  image_picker: ^1.0.7

  # ðŸ”¹ Ãcones iOS (opcional)
  cupertino_icons: ^1.0.8
  record: ^6.1.2
  audioplayers: ^6.5.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  uuid: ^4.5.2
  zego_uikit_prebuilt_call: ^4.21.1
  emoji_picker_flutter: ^4.3.0

# DependÃªncias apenas para Desenvolvimento e Testes
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# ConfiguraÃ§Ãµes do Flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/